// GENERATED by tools/build-sample-data.mjs from data/sample-places.json. Do not edit.
// Natural Resources Canada, Canadian Geographical Names Database (CGNDB) search API. Open Government Licence - Canada (https://open.canada.ca/en/open-government-licence-canada).
// Real community points; the people and the dealer that use them are SAMPLE. No house numbers.
export const SAMPLE_PLACES = [
  {
    "name": "Springdale",
    "lat": 49.5119027,
    "lng": -56.0642695,
    "km_from_springdale": 0
  },
  {
    "name": "King's Point",
    "lat": 49.5807861,
    "lng": -56.208,
    "km_from_springdale": 12.9
  },
  {
    "name": "South Brook",
    "lat": 49.4029722,
    "lng": -56.089675,
    "km_from_springdale": 12.3
  },
  {
    "name": "Robert's Arm",
    "lat": 49.4766556,
    "lng": -55.8347694,
    "km_from_springdale": 17
  },
  {
    "name": "Pilley's Island",
    "lat": 49.5277056,
    "lng": -55.7158528,
    "km_from_springdale": 25.2
  },
  {
    "name": "Little Bay",
    "lat": 49.5992389,
    "lng": -55.9518361,
    "km_from_springdale": 12.7
  },
  {
    "name": "Beachside",
    "lat": 49.6428889,
    "lng": -55.8991139,
    "km_from_springdale": 18.8
  },
  {
    "name": "St. Patrick's",
    "lat": 49.566667,
    "lng": -55.9825,
    "km_from_springdale": 8.5
  },
  {
    "name": "Harry's Harbour",
    "lat": 49.7002778,
    "lng": -55.9238889,
    "km_from_springdale": 23.3
  },
  {
    "name": "Middle Arm",
    "lat": 49.7030277,
    "lng": -56.1148445,
    "km_from_springdale": 21.6
  },
  {
    "name": "Jackson's Cove",
    "lat": 49.6852778,
    "lng": -55.9936111,
    "km_from_springdale": 19.9
  },
  {
    "name": "Sheppardville",
    "lat": 49.4508334,
    "lng": -56.4316666,
    "km_from_springdale": 27.4
  },
  {
    "name": "Triton",
    "lat": 49.518325,
    "lng": -55.619875,
    "km_from_springdale": 32.1
  },
  {
    "name": "Baie Verte",
    "lat": 49.9087083,
    "lng": -56.1946584,
    "km_from_springdale": 45.1
  },
  {
    "name": "Buchans",
    "lat": 48.8238,
    "lng": -56.8490694,
    "km_from_springdale": 95.4
  }
]
